# Discussion 01: More Python Basics & Arrays 

Welcome to Discussion 02! At the end of last week's discussion, we got a sneak peak of arrays and tables. This week, we will continue to go over some Python Basics as well as go into depth on some of these data structures. 

You can get additional help on these topics in the course [textbook](https://eldridgejm.github.io/dive_into_data_science/front.html)

[Here](https://ucsd-ets.github.io/dsc10-2020-fa/published/default/reference/babypandas-reference.pdf) is a pointer to that reference sheet we saw last time.

In [1]:
# please don't change this cell, but do make sure to run it
import babypandas as bpd
import matplotlib.pyplot as plt
import numpy as np 
import math
import otter
grader = otter.Notebook()

from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.update(
    "livereveal", {
        "width": "90%",
        "height": "90%",
        "scroll": True,
})

{'width': '90%', 'height': '90%', 'scroll': True}

# What we'll cover:
---
More Python Basics:
- Arrays
- Variables
- Functions

How to work with:
- Arrays

# Part 1: More Python Basics

## Data Types in Python Continued:

### Arrays

In [2]:
# Lists
type([[5,2,'hello'], '1', 2, '3'])

list

In [3]:
# Lists can contain any type of data
['hi', ['how', 'are', 'you']]

['hi', ['how', 'are', 'you']]

### NumPy Arrays

NumPy Arrays will fit all data to **the same type**

In [4]:
import numpy as np

np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
print("overall type:", type(np.array([1, 2, 3])))
print("type of individual elements:", np.array([1, 2, 3]).dtype)

overall type: <class 'numpy.ndarray'>
type of individual elements: int64


Recap:

All objects in Python have a type, some of which are primitive, some of which act more like containers.

If we ever forget what type something is, we can use `type()` to find out!

# Variables
---

In Python when you assign a variable like this:

`x = 4 + 3`

You're essentially telling Python this:

`From now on, please let the value of 'x' contain the value of 7.`

If you then re-assign the same variable name to a different value, the old value will be lost forever.

In [6]:
x = 4
y = "Why"
z = [4.0, "That's the dream..."]
class_choice = np.array(["Cake", 3.14])

print(x)
print(y)
print(z)
print(class_choice) 

4
Why
[4.0, "That's the dream..."]
['Cake' '3.14']


What happens if we assign x again?

In [7]:
print(x)

4


In [8]:
x = "string"
print(x)

string


Recall that variables assume the type of what you assign it to

In [9]:
print(type(x))
print(type(y))
print(type(z))
print(type(class_choice))

<class 'str'>
<class 'str'>
<class 'list'>
<class 'numpy.ndarray'>


We can even assign variables to other variables, this can get a bit tricky.

In [10]:
x = 1
y = x
x = 2

print("y == x?       ", y == x)

y == x?        False


Wait but I thought we just set `y = x`!

Recall that we're telling Python to assign y **to the value of** x, not directly to x!

What is the value of something then?
It's whatever is returned if you run it at the end of a cell.

In [11]:
# The value of x is
x

2

We can also perform operations on NumPy arrays.

In [12]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [13]:
x + y

array([5, 7, 9])

In [14]:
x * 2

array([2, 4, 6])

# Functions
---

Functions, like `print()`, allow us to easily run something with different <b>arguments</b>.

We can also define our own functions to allow us to run our own code multiple times with different arguments.

### Definitions:
<b>Parameter</b>: Variable in method definition. Ex: `def print(string_to_print):`

<b>Argument</b>: Actual value used in function calls. Ex: `print("hello")`

Kinda pedantic, they are often used interchangably and people will know what you mean either way.

Many functions take values as inputs.  
All functions will return a value (but that value may be `None`).

Just like all values in Python, these have a type!

So, it's important that we know what a function takes and what it returns.

This helps a lot when it comes to fixing bad code!

A Python function is called with the following format:

`function_name(arg_1, arg_2, ...)`

For example, `sum` takes a list (or array-like object) as a argument.  
The function `len` can take a list too.

In [15]:
sum(np.array([1, 2, 3]))

6

In [16]:
len(np.array([1, 2, 3]))

3

And other functions, like `pow` take more than one argument.

In [17]:
help(pow)

Help on built-in function pow in module builtins:

pow(base, exp, mod=None)
    Equivalent to base**exp with 2 arguments or base**exp % mod with 3 arguments
    
    Some types, such as ints, are able to use a more efficient algorithm when
    invoked using the three argument form.



In [18]:
pow(1.618, 2)

2.6179240000000004

Some objects have their own functions!  
To call this, you need to use "dot notation", it looks like this:


`some_object.func_name(some_arg_1, some_arg_2, ...)`

In [19]:
"hello world".title()

'Hello World'

In [20]:
"hello world".replace('world', 'DSC 10')

'hello DSC 10'

We can assign a variable as the result of a function the same way we assign any variable!

In [21]:
x = pow(8, 2)
x

64

<b>Bonus Question</b>: What is the return type of `print("hello")`?

In [22]:
x = print("hello")
type(x)

hello


NoneType

<b>Bonus Bonus Question</b>: What will be printed out?

`
f = print
x = f("hello")
f(type(x))
`

In [23]:
# f = print
x = print("hello")
print(type(x))

hello
<class 'NoneType'>


# Practice questions part 1
---

Try out these problems to get a bit more familiar with NumPy arrays.

## Question 1.1

We have 5 triangles.
`base` measures the base of each triangle, `height` measures the height.

What is the average area of a triangle in the data set?

In [24]:
base = np.array([3, 1, 3, 5, 2])
height = np.array([6, 2, 7, 7, 1])

```
BEGIN QUESTION
name: q11
```

In [25]:
average_area = np.mean(0.5 * base * height) # SOLUTION
average_area

7.8

In [26]:
## TEST ##
math.isclose(average_area, 7.8)

True

## Recall: Ranges
We can use this to easily generate sequential NumPy arrays.

In [27]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [28]:
np.arange(3, 16, 4)

array([ 3,  7, 11, 15])

## Question 1.2

Create an array that runs from 0 to 50 (included), with steps of 5 as below:

0, 5, 10, ..., 45, 50

```
BEGIN QUESTION
name: q12
```

In [29]:
zero_to_fifty_array = np.arange(0,51,5) # SOLUTION
zero_to_fifty_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [30]:
## TEST ## 
np.array_equal(zero_to_fifty_array, np.array([0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50]))

True

## Question 1.3

Using code, create the array:

[4, 8, 16, 32, 64]

```
BEGIN QUESTION
name: q13
```

In [31]:
four_to_sixty_four_array = pow(2,np.arange(2,7)) # SOLUTION
four_to_sixty_four_array

array([ 4,  8, 16, 32, 64])

In [32]:
## TEST ##
np.array_equal(four_to_sixty_four_array, np.array([4, 8, 16, 32, 64]))

True

## FYI: Other array creation functions

In [33]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [34]:
zeros_array = np.zeros(5)
zeros_array

array([0., 0., 0., 0., 0.])

# Part 2: Arrays

## Arrays vs. Lists

---
Arrays and lists are helpful when we want to store and manipulate **sequences** of data

##### Lists
- Built into Python
- Friendly with different data types
- EXTREMELY SLOW

##### Arrays
- Not built inot Python directly (that's why we have NumPy!)
- Elements must be the same data type
- MUCH FASTER


## Array Problems

In [35]:
some_array = np.array([6, 1, 9, 5, 2, 3, 4, 3, 2, 4])

**Question 1** : How many elements are in ```some_array```?

```
BEGIN QUESTION
name: q11
```

In [36]:
num_elems = some_array.size # SOLUTION
num_elems

10

In [37]:
## TEST ##
num_elems == 10

True

**Question 2** : How do we access the *first* element of ```some_array```?

```
BEGIN QUESTION
name: q12
```

In [38]:
first_elem = some_array[0] # SOLUTION
first_elem

6

In [39]:
## TEST ##
first_elem == 6

True

In [40]:
last_elem = some_array[-1] # SOLUTION
last_elem

4

In [41]:
## TEST ##
last_elem == -4

False

In [42]:
last_index = some_array.size - 1 # SOLUTION NO PROMPT
last_elem = some_array[last_index] # SOLUTION NO PROMPT

**Question 4** : What happens when we do ```some_array[-2]```?

In [43]:
some_array

array([6, 1, 9, 5, 2, 3, 4, 3, 2, 4])

In [44]:
some_array[-2]

2

In [45]:
neg_2 = some_array[-2] # SOLUTION NO PROMPT

**Question 5 - BONUS** : How do we make a new array that contains only the first 5 elements from ```some_array```? 

```
BEGIN QUESTION
name: q15
```

In [46]:
first_five = some_array[:5] # SOLUTION
first_five

array([6, 1, 9, 5, 2])

In [47]:
## TEST ##
(first_five == np.array([6,1,9,5,2])).all()

True

In [48]:
array_1 = np.array([1,2,3,4,5,6,7,8])
array_2 = np.array([6,7,8,9,10,11,12,13])

**Question 6** : How to we get the element-wise sum of ```some_array``` and ```some_array_2```?

```
BEGIN QUESTION
name: q16
```

In [49]:
elem_wise_sum = array_1 + array_2 # SOLUTION
elem_wise_sum

array([ 7,  9, 11, 13, 15, 17, 19, 21])

In [50]:
## TEST ##
(elem_wise_sum == np.array([ 7,  9, 11, 13, 15, 17, 19, 21])).all()

True

**Question 7** : How to we get the max element from ```some_array```?

```
BEGIN QUESTION
name: q17
```

In [51]:
max_elem = max(some_array) # SOLUTION
max_elem

9

In [52]:
## TEST ##
max_elem == 9

True

In [53]:
max_elem = some_array.max() # SOLUTION NO PROMPT

**Question 8 - BONUS** : How to we get the average of first 6 elements from ```some_array```?

```
BEGIN QUESTION
name: q18
```

In [54]:
first_six_average = np.mean(some_array[:6]) # SOLUTION
first_six_average

4.333333333333333

In [55]:
## TEST ##
import math
math.isclose(first_six_average, 4.33333333333333)

True

**Question 9** : How to we make an array with every integer under 13

```
BEGIN QUESTION
name: q19
```

In [56]:
under_13 = np.arange(13) # SOLUTION
under_13

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [57]:
## TEST ##
(under_13 == np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])).all()

True

**Question 10** : How do we make an array of [6,9,12,15,18,21]

```
BEGIN QUESTION
name: q110
```

In [58]:
threes_array = np.arange(6,22,3) # SOLUTION
threes_array

array([ 6,  9, 12, 15, 18, 21])

In [59]:
## TEST ##
(threes_array == np.array([ 6,  9, 12, 15, 18, 21])).all()

True

**Question 11** : How do we make an array of 2 to the power of from 2 to 6, aka [4,8,16,32,64]?

```
BEGIN QUESTION
name: q111
```

In [60]:
powers_of_two = pow(2,np.arange(2,7)) # SOLUTION
powers_of_two

array([ 4,  8, 16, 32, 64])

In [61]:
## TEST ##
(powers_of_two == np.array([ 4,  8, 16, 32, 64])).all()

True

**Remember!** NumPy Arrays will fit all data to the same type:

In [62]:
random_array = np.array([45,"hello", True, 987, 34.5, "Yes"])
random_array

array(['45', 'hello', 'True', '987', '34.5', 'Yes'], dtype='<U21')

In [63]:
#But Lists will not:
random_list = ['hello', 'there', 'buddy', 43, True, 38.9, 'DSC 10']
random_list

['hello', 'there', 'buddy', 43, True, 38.9, 'DSC 10']

In [64]:
print(type(random_array))
print(type(random_list))

<class 'numpy.ndarray'>
<class 'list'>
